tasks:
  - init: curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash
  - init: brew install k9s
  - init: brew install stern
  - init: brew install octant
  - openMode: split-bottom
    command: sudo docker-up SplitTerminal
  - openIn: right
    command: docker run hello-world
