apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Chart.Name }}-ingress

spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.app.networking.ingressfqdn }}
      http:
        paths:
        - path: /order
          backend:
            serviceName: {{ .Chart.Name }}-service
            servicePort: 80
