name: Deploy to AKS

on:
  workflow_dispatch:
      
jobs:
  deployToAks:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Kubeconfig
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          AKSRESOURCEGROUP: 'tc-showcase-test'
          AKSNAME: 'k8s-tc-showcase-test'
        working-directory: ./resources/pipelines/helperscripts
        run: |
              ./getKubeconfig.sh

      - name: Get Secrets
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
        working-directory: ./resources/pipelines/helperscripts
        run: |
              ./getKeyVaultSecrets.sh

      - name: Deploy via Helm
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          AKSRESOURCEGROUP: 'tc-showcase-test'
          AKSNAME: 'k8s-tc-showcase-test'
        run: |
              docker run \
                -v "$(pwd)/resources/k8s":/apps \
                -v "$(pwd)/resources/pipelines/helperscripts/kubeconfig":/root/.kube \
                alpine/helm \
                    upgrade orderdomain ./ \
                        --namespace orderdomain \
                        --install \
                        --values values.yaml \
                        --set app.dbconfig.host="${DBFQDN}" \
                        --set app.dbconfig.user="${DBUSER}@tc-showcase-test-psql" \
                        --set app.dbconfig.password="${DBPWD}" \
                        --set app.dbconfig.schema="test" \
                        --set app.dbconfig.name="orderdomain" \
                        --set app.networking.ingressfqdn="${INGRESSFQDN}"

      - name: Cleanup
        working-directory: ./resources/pipelines/helperscripts
        run: |
              sudo rm -rf kubeconfig
              echo "DBUSER=asdf" >> $GITHUB_ENV
              echo "DBPWD=asdf" >> $GITHUB_ENV
              echo "DBFQDN=asdf" >> $GITHUB_ENV
              echo "INGRESSFQDN=asdf" >> $GITHUB_ENV
