name: Deploy to AKS

on:
  push:
    branches: [ migrateToPsql ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get Kubeconfig
        env:
          ARM_CLIENT_ID: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.TC_SHOWCASE_ARM_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.TC_SHOWCASE_ARM_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.TC_SHOWCASE_ARM_TENANT_ID }}
          AKSRESOURCEGROUP: 'tc-showcase-test'
          AKSNAME: 'k8s-tc-showcase-test'
        run: |
              #!/bin/bash
              set -e

              az login --service-principal \
                  -u $ARM_CLIENT_ID \
                  -p $ARM_CLIENT_SECRET \
                  --tenant $ARM_TENANT_ID \
                  --allow-no-subscriptions > /dev/null

              az aks get-credentials --resource-group $AKSRESOURCEGROUP --name $AKSNAME --file kubeconfig/.kubeconfig

              ls -al
              pwd

